# -*- coding: utf-8 -*-
{
    'name': 'Tasys permission',
    'summary': """Tasys permission """,
    'description': """
        Tasys permission
    """,
    'author': "TASYS",
    'website': "",
    'category': 'tasys',
    'version': '1.0',
    'depends': [
        'base',
        'account',
        'stock',
        'sale',
        'sales_team',
        'delivery',
        'dashboard_inventory',
        'account_batch_payment',
        'tas_payment'
    ],
    'images': [
        'static/description/icon.png',
    ],
    'data': [
        'security/group_user_security.xml',
        'security/ir.model.access.csv',
        'security_category_manager/ir.model.access.csv',
        'security_wh_supervisor/ir.model.access.csv',
        'views/administrator_menus.xml',
        'views/account/account_move_views.xml',
        'views/accounting_customer_payments/account_payment.xml',
        # 'views/export_groups.xml',
        # 'views/accounting_menu_groups.xml',
        # 'views/inventory_menu_groups.xml',
        # 'views/sale_menu_groups.xml',
        # 'views/purchase_menu_groups.xml',
        'views/form_no_create_comodel.xml',
        'views/sale_category_manager.xml',
        'views/sale_category_executive.xml',
        'views/sale_cs_manager.xml',
        'views/sale_cs_executive.xml',
        'views/inventory_category_manager.xml',
        'views/sale_menu_wh_supervisor.xml',
        'views/sale_menu_wh.xml',
        'views/sale_menu_sourcing.xml',
        'views/inventory_menu_wh_supervisor.xml',
        'views/inventory_menu_wh.xml',
        'views/inventory_menu_sourcing.xml',
        'views/purchase_menu_wh.xml',
        'views/purchase_menu_wh_supervisor.xml',
        'views/purchase_menu_sourcing.xml',
        'views/inventory_cs_manager.xml',
        'views/inventory_cs_executive.xml',
        'views/inventory_category_executive.xml',
        'views/sale_accountant_manager.xml',
        'views/inventory_category_manager.xml',
        'views/purchase_category_manager.xml',
        'views/purchase_category_executive.xml',
        'views/purchase_cs_manager.xml',
        'views/accounting_category_manager.xml',
        'views/accounting_cs_manager.xml',
        'views/accounting_cs_executive.xml',
        'views/accounting_sales_lead.xml',
        'views/accounting_sales_executive.xml',
        'views/accounting_accountant_manager.xml',
        'views/accounting_accountant_executive.xml',
        'views/accounting_menu_wh_supervisor.xml',
        'views/accounting_menu_wh.xml',
        'views/accounting_menu_sourcing.xml',
        'views/inventory_accountant_manager.xml',
        'views/purchase_accountant_manager.xml',
        'views/inventory_accountant_executive.xml',
        'views/purchase_accountant_executive.xml',
        'views/sale_accountant_executive.xml',
        # 'views/purchase_sales_lead.xml',
        'views/sale_sales_lead.xml',
        'views/sale_sales_executive.xml',
        'views/accounting_category_executive.xml',
        'views/product/product_template_views.xml',
        'views/res_partner_views/res_partner_views_permission.xml',
        'views/stock/stock_picking.xml',
        'views/sale/sale_order.xml',
        'views/setting_wh_supervisor.xml',
        'views/setting_wh.xml',
        'views/setting_sourcing.xml',
        'views/inventory_sales_lead.xml',
        'views/inventory_sales_executive.xml',

    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
